# -*- coding: utf-8 -*-
"""Análise_Python_Pandas_Excel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O9oS1LjAG9nRLjEy64L_c7XWvkGf-Ncq
"""

import pandas as pd 
import matplotlib.pyplot as plt
plt.style.use("seaborn")

from google.colab import files
arq = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")
df.head()

df.shape

df.dtypes

# RECEITA TOTAL
df["Valor Venda"].sum()

# CRIANDO COLUNA DE CUSTO
df["custo"] = df["Custo Unitário"].mul(df["Quantidade"])
df.head(1)

# CUSTO TOTAL
round(df["custo"].sum(),2)

# LUCRO TOTAL
df["lucro"] = df["Valor Venda"] - df["custo"]

df.head(1)

#TOTAL LUCRO
round(df["lucro"].sum(),2)

# TEMPO DE ENVIO PARA PRODUTOS
df["Tempo_envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.head(1)

# MÉDIO PARA O TEMPO DE ENVIO
df.groupby("Marca")["Tempo_envio"].mean()

#LUCRO POR ANO E POR MARCA
df.groupby([df["Data Venda"].dt.year, "Marca"])["lucro"].sum()

pd.options.display.float_format = '{:20; 2f}'.format

#TOTAL DE PRODUTOS VEDIDOS
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

# GRÁFICO - TOTAL DE PRODUTOS VENDIDOS
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total de Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

df.groupby(df["Data Venda"].dt.year)["lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

df_2009 = df[df["Data Venda"].dt.year == 2009]

df_2009.groupby(df_2009["Data Venda"].dt.month)["lucro"].sum().plot(title="Lucro x Mês")
plt.xlabel("Mês")
plt.ylabel("Lucro");

df.to_csv("df_vendas_novo.csv",index=False)